name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Folder
        run: |
          zip -r joiplay.zip Game.exe Game.ini x64-msvcrt-ruby310.dll .nomedia *.json gems

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          fail_on_unmatched_files: true
          files: |
            joiplay.zip
